# Generated by Django 3.2.9 on 2022-05-31 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220531_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachermodel',
            old_name='user_id',
            new_name='t_user_id',
        ),
    ]
