# Generated by Django 3.2.9 on 2022-05-31 14:50

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220531_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('image', models.ImageField(null=True, upload_to='media/images/couse_section_images')),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='account.coursemodel')),
            ],
            options={
                'verbose_name': 'Section of courses',
                'verbose_name_plural': 'Sections of courses',
            },
        ),
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='media/documents/lessons')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/videos/lessons')),
                ('image_video', models.ImageField(blank=True, null=True, upload_to='media/images/for_videos')),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='you should use from this section for explaining the lesson', null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.coursemodel', verbose_name='Course')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.coursesection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Lessons',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='CourseCommentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=80, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.coursemodel')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commentary for course',
                'verbose_name_plural': 'Commentaries for courses',
            },
        ),
    ]
