# Generated by Django 3.2.9 on 2022-05-31 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_coursecommentary_coursesection_lessonmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsmodels',
            name='courses',
        ),
    ]
