# Generated by Django 3.2.9 on 2022-05-31 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_coursemodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='students',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='finished_users',
            field=models.ManyToManyField(help_text='Course finished users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='learners',
            field=models.ManyToManyField(related_name='learners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='fn_cs_users',
            field=models.ManyToManyField(help_text='Course section finished users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='fn_l_users',
            field=models.ManyToManyField(help_text='students which are finished the Lesson', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StudentsModels',
        ),
    ]
