# Generated by Django 3.2.9 on 2022-06-01 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20220531_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='finished_users',
            field=models.ManyToManyField(blank=True, help_text='Course finished users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='learners',
            field=models.ManyToManyField(blank=True, related_name='learners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='fn_cs_users',
            field=models.ManyToManyField(blank=True, help_text='Course section finished users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonmodel',
            name='fn_l_users',
            field=models.ManyToManyField(blank=True, help_text='students which are finished the Lesson', to=settings.AUTH_USER_MODEL),
        ),
    ]
