# Generated by Django 3.2.9 on 2022-06-01 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20220601_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('None', 'none'), ('Student', 'student'), ('Teacher', 'teacher'), ('Teacher_And_Student', 'teacher_and_student')], default='None', max_length=22),
        ),
        migrations.DeleteModel(
            name='TeacherModel',
        ),
    ]
