# Generated by Django 3.2.9 on 2022-06-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20220601_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=14, null=True, verbose_name='price by $(dollar)'),
        ),
    ]
