# Generated by Django 3.2.9 on 2022-06-01 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_coursemodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='finished_users',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='learners',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='specialize_id',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='fn_cs_users',
        ),
        migrations.RemoveField(
            model_name='lessonmodel',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='lessonmodel',
            name='fn_l_users',
        ),
        migrations.RemoveField(
            model_name='lessonmodel',
            name='section_id',
        ),
        migrations.DeleteModel(
            name='CourseCommentary',
        ),
        migrations.DeleteModel(
            name='CourseModel',
        ),
        migrations.DeleteModel(
            name='CourseSection',
        ),
        migrations.DeleteModel(
            name='LessonModel',
        ),
    ]
