# Generated by Django 3.2.9 on 2022-06-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/images/default_avatar.png', null=True, upload_to='images/user_avatars/'),
        ),
    ]
