# Generated by Django 3.2.9 on 2022-06-30 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('speacial_for', models.CharField(choices=[('everyone', 'everyone'), ('Student', 'student'), ('Teacher', 'teacher')], max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auther', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ads',
            },
        ),
    ]
