# Generated by Django 3.2.9 on 2022-06-30 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='ad_seen_by_users',
            field=models.ManyToManyField(related_name='seen_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
