# Generated by Django 3.2.9 on 2022-06-30 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0002_ads_ad_seen_by_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ad_seen_by_users',
            field=models.ManyToManyField(blank=True, related_name='seen_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
