# Generated by Django 3.2.9 on 2022-06-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.IntegerField(choices=[(None, 'none'), (10, '10 minutes'), (15, '15 minutes'), (20, '20 minutes'), (30, '30 minutes'), (40, '40 minutes'), (1, '1 hour'), (2, '2 hours')], null=True),
        ),
    ]
