# Generated by Django 3.2.9 on 2022-06-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_test_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('ANSWER1', 'answer1'), ('ANSWER2', 'answer2'), ('ANSWER3', 'answer3'), ('ANSWER4', 'answer4')], default='ANSWER1', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.IntegerField(choices=[(None, 'none'), (10, '10 minutes'), (15, '15 minutes'), (20, '20 minutes'), (30, '30 minutes'), (40, '40 minutes'), (1, '1 hour'), (2, '2 hours')], default=None, null=True),
        ),
    ]
