# Generated by Django 3.2.9 on 2022-06-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20220625_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.PositiveBigIntegerField(default=0, help_text="Enter duration of the test         If you enter only 0 i't means Test's duration time will be limitless", null=True),
        ),
    ]
