# Generated by Django 3.2.9 on 2022-06-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_test_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='is_passed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
