# Generated by Django 3.2.9 on 2022-05-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecializeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='media/images/subject_specialize_images')),
                ('desciption', models.CharField(help_text='Write something about specialize or subjects. For instance about its advantages', max_length=250, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Specialize or Subject',
                'verbose_name_plural': 'Specializes or Subjects',
            },
        ),
    ]
