# Generated by Django 3.2.9 on 2022-05-31 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220531_1910'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('image', models.ImageField(null=True, upload_to='media/images/course_images')),
                ('description', models.CharField(max_length=250, null=True)),
                ('price', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='price by $(dollar)')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialize_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.specializemodel')),
                ('students', models.ManyToManyField(to='account.StudentsModels')),
                ('teacher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.teachermodel')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
