# Generated by Django 3.2.9 on 2022-05-31 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseModel',
        ),
    ]
