# Generated by Django 3.2.9 on 2022-06-01 10:58

import ckeditor.fields
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_delete_coursemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/course_images')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='price by $(dollar)')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_users', models.ManyToManyField(blank=True, help_text='Course finished users', to=settings.AUTH_USER_MODEL)),
                ('learners', models.ManyToManyField(blank=True, related_name='learners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/couse_section_images')),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.coursemodel')),
                ('fn_cs_users', models.ManyToManyField(blank=True, help_text='Course section finished users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Section of courses',
                'verbose_name_plural': 'Sections of courses',
            },
        ),
        migrations.AlterField(
            model_name='specializemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/subject_specialize_images'),
        ),
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/lessons')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/lessons')),
                ('image_video', models.ImageField(blank=True, null=True, upload_to='media/images/for_videos')),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='you should use from this section for explaining the lesson', null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodel', verbose_name='Course')),
                ('fn_l_users', models.ManyToManyField(blank=True, help_text='students which are finished the Lesson', to=settings.AUTH_USER_MODEL)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursesection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Lessons',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='specialize_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.specializemodel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CourseCommentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=80, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodel')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commentary for course',
                'verbose_name_plural': 'Commentaries for courses',
            },
        ),
    ]
