# Generated by Django 3.2.9 on 2022-06-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20220604_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodel',
            name='image_video',
            field=models.ImageField(blank=True, null=True, upload_to='images/for_videos'),
        ),
    ]
