# Generated by Django 3.2.9 on 2022-06-26 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_lessonmodel_image_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='courses.coursemodel'),
        ),
        migrations.AlterField(
            model_name='lessonmodel',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='courses.coursesection', verbose_name='Section'),
        ),
    ]
