# Generated by Django 3.2.9 on 2022-07-05 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resources.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recievers', models.CharField(choices=[('everyone', 'everyone'), ('my_students', 'my students')], default='everyone', max_length=11)),
                ('file', models.FileField(upload_to='resources', validators=[resources.validators.valid_file_type_for_documents, resources.validators.valid_file_size_for_documents])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='from')),
            ],
        ),
    ]
