# Generated by Django 3.2.9 on 2022-07-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='document_type',
            field=models.CharField(choices=[('books', 'books'), ('articles', 'articles'), ('scientific_article', 'scientific article'), ('usefull', 'usefull')], default='books', max_length=19),
        ),
    ]
